# Generated by Google Gemini (2025-03-22)
# Prompt:
#   I have two python lists, A and B. each is a list of strings.
#   From these i need to generate a new list, C, of entries in A that don't have an "ends with" match from B.
#   Please write me some python code to generate list C from lists A and B as I described. 
# 

def filter_list_by_endings(A, B):
  """
  Generates a new list C containing entries from list A that do not have 
  an "ends with" match from any string in list B.

  Args:
    A: A list of strings.
    B: A list of strings representing potential endings.

  Returns:
    A new list C containing strings from A that don't end with any string in B.
  """
  C = []
  for a_item in A:
    ends_with_match = False
    for b_item in B:
      if a_item.endswith(b_item):
        ends_with_match = True
        break  # No need to check other endings if a match is found
    if not ends_with_match:
      C.append(a_item)
  return C

# Example usage:
A = ["apple_pie", "banana", "cherry_tree", "grape", "orange_juice"]
B = ["pie", "tree", "juice"]

C = filter_list_by_endings(A, B)
print(C)  # Output: ['banana', 'grape']